[preferred]
default=kde
org.freedesktop.impl.portal.Screencast=kde
org.freedesktop.impl.portal.Screenshot=kde
org.freedesktop.impl.portal.RemoteDesktop=kde
org.freedesktop.impl.portal.Settings=kde;gtk;
org.freedesktop.impl.portal.Secret=kwallet
