# === APPEARANCE ===
background_opacity 1
wm_class kitty
wayland_titlebar_icon kitty
dynamic_background_opacity no
font_family JetBrainsMono Nerd Font
font_size 11.0
cursor_shape block
cursor_blink_interval 0
window_padding_width 0
#hide_window_decorations titlebar-only

# === MOUSE BEHAVIOR ===
copy_on_select clipboard
mouse_map right press ungrabbed noop
mouse_map right release ungrabbed paste_from_clipboard

# === TABS ===
tab_bar_style powerline
tab_bar_edge bottom
tab_separator " | "

# === SCROLLING ===
wheel_scroll_multiplier 5.0
inactive_text_alpha 0.8

# === PERFORMANCE ===
sync_to_monitor yes
remember_window_size yes
initial_window_width 800
initial_window_height 600

map ctrl+tab goto_tab -1
map ctrl+shift+t new_tab
map ctrl+w close_tab

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
