[text]
appendEmptyLine=true
autoBracket=false
autoReplace=false
autoSave=false
autoSaveInterval=1
darkBgColorValue=16
darkColorScheme=true
dateFormat=
dictionaryPath=
executeCommand=
executeScripts=false
font="Monospace,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,,0,0"
inertialScrolling=false
lightBgColorValue=255
lineNumbers=false
maxSHSize=2
noIndent=false
noSyntaxHighlighting=false
noWrap=false
pastePaths=false
recentFiles=/mnt/stash/Backups/README.txt
recentFilesNumber=10
recentOpened=false
removeTrailingSpaces=false
saveLastFilesList=false
saveUnmodified=false
selectionHighlighting=false
showEndings=false
showWhiteSpace=false
skipNonText=true
spellCheckFromStart=false
textMargin=false
textTabSize=4
thickCursor=false
vLineDistance=-80

[window]
closeWithLastTab=false
disableMenubarAccel=false
fullscreen=false
hideSearchbar=true
hideSingleTab=false
max=false
menubarTitle=true
nativeDialog=true
noMenubar=false
noToolbar=true
openInWindows=false
position=@Point(0 0)
prefSize=@Size(650 536)
sharedSearchHistory=false
showCursorPos=false
showLangSelector=false
showStatusbar=false
sidePaneMode=false
size=@Size(946 493)
splitterPos=150
startSize=@Size(700 500)
sysIcons=true
tabPosition=0
tabWrapAround=false
